# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1caae83f34c0a95f112c0d69b7bd3947cee0fc38533dd3b9a3814423c068b3e1f788c5b73655df04d9fc27112ea625ac98633e89fa1e6c5cd1c0af0d55208830

test:
  secret_key_base: 0a95eacb27f8e6cdec4aedce7f18d71ce1fdd74c90b38110efcc3ae3146a681b32fa59f034d69a94755bde45ee0a116b4d3197d007688776f08b18a9a612bd9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
